# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kdxv7wqLRWRD8pQoObkt4_mjMpPkOBIY
"""

def create_python_banner():
    banner = """
   @   @ @@@@@  @@@@@@ @@@@@@ @.   @
   @@  @ @   @  @      @      @ @  @
   @ @ @ @@@@@  @      @@@@@  @  @ @
   @  @@ @   @  @      @      @   @@
   @   @ @   @  @@@@@@ @@@@@  @    @
    """
    return banner
print(create_python_banner())
# Menerima input dari pengguna
angka_awal = int(input("Masukkan angka awal: "))
angka_akhir = int(input("Masukkan angka akhir: "))

# Memastikan angka awal lebih kecil dari angka akhir
if angka_awal > angka_akhir:
    angka_awal, angka_akhir = angka_akhir, angka_awal

# Menampilkan angka dengan urutan yang dimodifikasi
for i in range(angka_awal, (angka_akhir // 2) + 1):
    j = angka_akhir - i + angka_awal
    print(f"{i} | {j}")

def create_python_banner():
    banner = """
   @   @ @@@@@  @@@@@@ @@@@@@ @.   @
   @@  @ @   @  @      @      @ @  @
   @ @ @ @@@@@  @      @@@@@  @  @ @
   @  @@ @   @  @      @      @   @@
   @   @ @   @  @@@@@@ @@@@@  @    @
    """
    return banner
print(create_python_banner())

# Menerima input total harga belanjaan
total_harga = int(input("Masukkan total harga belanjaan dalam Rupiah: "))

# Menerima input jumlah uang dari pelanggan
jumlah_uang = int(input("Masukkan jumlah uang yang diberikan dalam Rupiah: "))

# Menghitung kembalian
kembalian = jumlah_uang - total_harga

# Daftar nilai nominal uang lembar dalam Rupiah
lembar_uang = [100000, 50000, 20000, 10000, 5000, 2000, 1000]

# Inisialisasi dictionary untuk menyimpan jumlah lembar uang yang dibutuhkan
jumlah_lembar_uang = {}

# Menghitung jumlah lembar uang yang dibutuhkan
for nominal in lembar_uang:
    if kembalian >= nominal:
        jumlah_lembar = kembalian // nominal
        kembalian = kembalian % nominal
        jumlah_lembar_uang[nominal] = jumlah_lembar

# Menampilkan kembalian
print("Kembalian:Rp", jumlah_uang - total_harga,)

# Menampilkan jumlah lembar uang yang dibutuhkan
for nominal, jumlah in jumlah_lembar_uang.items():
    print("uang Rp", nominal,"=",jumlah,"lembar" )